-- MySQL Script generated by MySQL Workbench
-- Sat Oct 23 20:08:16 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banking
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `banking` ;

-- -----------------------------------------------------
-- Schema banking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banking` DEFAULT CHARACTER SET utf8 ;
USE `banking` ;

-- -----------------------------------------------------
-- Table `banking`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`users` ;

CREATE TABLE IF NOT EXISTS `banking`.`users` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(10) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `remember_token` VARCHAR(45) NULL,
  `email_verified_at` TIMESTAMP NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  `deleted_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `banking`.`user_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`user_address` ;

CREATE TABLE IF NOT EXISTS `banking`.`user_address` (
  `id` BIGINT NOT NULL,
  `users_id` BIGINT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `state` VARCHAR(100) NOT NULL,
  `city` VARCHAR(60) NOT NULL,
  `colony` VARCHAR(100) NOT NULL,
  `zip_code` VARCHAR(10) NOT NULL,
  `address` VARCHAR(120) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_user_address_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_address_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`mipymes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`mipymes` ;

CREATE TABLE IF NOT EXISTS `banking`.`mipymes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT NOT NULL,
  `name` VARCHAR(120) NULL,
  `giro` VARCHAR(120) NULL,
  `is_physical_store` TINYINT NOT NULL DEFAULT 0,
  `num_employes` INT NOT NULL DEFAULT 1,
  `rfc` VARCHAR(20) NULL,
  `address` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_mipymes_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_mipymes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`ranks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`ranks` ;

CREATE TABLE IF NOT EXISTS `banking`.`ranks` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `requirements` JSON NOT NULL,
  `points` INT NULL,
  `badge` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`user_rank`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`user_rank` ;

CREATE TABLE IF NOT EXISTS `banking`.`user_rank` (
  `id` INT NOT NULL,
  `ranks_id` BIGINT NOT NULL,
  `users_id` BIGINT NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_levels_users1_idx` (`users_id` ASC) VISIBLE,
  UNIQUE INDEX `users_id_UNIQUE` (`users_id` ASC) VISIBLE,
  INDEX `fk_user_rank_ranks1_idx` (`ranks_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_levels_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_rank_ranks1`
    FOREIGN KEY (`ranks_id`)
    REFERENCES `banking`.`ranks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`missions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`missions` ;

CREATE TABLE IF NOT EXISTS `banking`.`missions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `mission` VARCHAR(150) NULL,
  `description` TEXT NULL,
  `icon` TEXT NULL,
  `status` TINYINT(1) NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`user_missions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`user_missions` ;

CREATE TABLE IF NOT EXISTS `banking`.`user_missions` (
  `missions_id` INT NOT NULL,
  `users_id` BIGINT NOT NULL,
  `status` ENUM('started', 'in_process', 'completed') NOT NULL DEFAULT 'started',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  INDEX `fk_user_missions_missions1_idx` (`missions_id` ASC) VISIBLE,
  INDEX `fk_user_missions_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_missions_missions1`
    FOREIGN KEY (`missions_id`)
    REFERENCES `banking`.`missions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_missions_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`accounts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`accounts` ;

CREATE TABLE IF NOT EXISTS `banking`.`accounts` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT NOT NULL,
  `available-limit` DECIMAL NOT NULL DEFAULT 0.00,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NULL,
  `updated_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_accounts_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_accounts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`cards` ;

CREATE TABLE IF NOT EXISTS `banking`.`cards` (
  `id` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`transactions` ;

CREATE TABLE IF NOT EXISTS `banking`.`transactions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `accounts_id` BIGINT NOT NULL,
  `merchant` VARCHAR(45) NULL,
  `amount` DECIMAL NOT NULL DEFAULT 0.00,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_transactions_accounts1_idx` (`accounts_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_accounts1`
    FOREIGN KEY (`accounts_id`)
    REFERENCES `banking`.`accounts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`user_cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`user_cards` ;

CREATE TABLE IF NOT EXISTS `banking`.`user_cards` (
  `users_id` BIGINT NOT NULL,
  `cards_id` INT NOT NULL,
  INDEX `fk_user_cards_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_user_cards_cards1_idx` (`cards_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_cards_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_cards_cards1`
    FOREIGN KEY (`cards_id`)
    REFERENCES `banking`.`cards` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banking`.`user_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banking`.`user_profile` ;

CREATE TABLE IF NOT EXISTS `banking`.`user_profile` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `users_id` BIGINT NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `sex` VARCHAR(45) NULL,
  `first_last_name` VARCHAR(45) NULL,
  `second_last_name` VARCHAR(45) NULL,
  `birthdate` VARCHAR(45) NULL,
  `photo` TEXT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_user_profile_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_profile_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `banking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
